apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: color-flask-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: k8s
    repoURL: https://github.com/nightmar39/bg-flask-color.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: color-bg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
